---
output:
  word_document: default
  html_document: default
---

### Pricing

The DWC plattform was developed under an open licence and was developed with public funding. The software is free for download and use.
\
\

### Use of the web plattform

The use of the webplattfrom is generally free of charge. Additional costs maybe charged if the user wants to use the verification and prediction support service. For using the plattform the user has to create a user account.

\

#### Calibration / Fitting

After setting up a user account, the user can upload FIB data and suitable predictor variables as pleased. The user may create as many bathing spots as * wants. Based on the outcomes of the fitting/calibration process the user can decide for each bathing spot individually whether predictions should be calculated.

\

#### Verification as a Service (Vaas)

In principle, it is possible to use the DWC web plattform with fake data. If user what to increase the credibility of their models the user may want to have a third party verification of the input data and a detailed documentation of the full modeling process. Vaas is a service provided by **company xyz** to personaly check the data provided by the user and certificate the modeling process. This is a individual service. Fees depend on the complexity of the provided input data which may differ case-by-case.

\

#### Using the prediction module

In contrast to the model calibration module of the plattform, the prediction module requires contineous server ressources and support for operation and maintenance. 

\

#### Prediction as a Service (PaaS)

The use of the prediction module requires that the necessary data for prediciton are transfered regulary to the plattfrom. This can be implemented by the user himself by providing a transfer link to the plattform. If the user has not a lot of experience in implementing these kind of data format conversions, **company xyz** offers to support these data cleaning procedures. Fees depend on the complexity of the problem and may be negotiated on a case-by-case basis. 







