# Generated by Django 3.0.8 on 2020-07-28 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rainstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainstation', to='ews.RainStation')),
            ],
        ),
    ]
