# Generated by Django 3.0.8 on 2020-07-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0004_auto_20200729_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredata',
            old_name='rainstation',
            new_name='station',
        ),
    ]
