# Generated by Django 3.0.8 on 2020-07-29 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0006_auto_20200729_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='feature_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_type', to='ews.FeatureType'),
        ),
    ]
