# Generated by Django 3.0.8 on 2020-07-31 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0007_auto_20200729_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredata',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='ews.Station'),
        ),
    ]
