# Generated by Django 3.0.8 on 2020-08-04 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ews', '0008_auto_20200731_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathingspot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
