# Generated by Django 3.0.8 on 2020-11-13 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ews', '0010_station_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathingspot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bathing_spots', to=settings.AUTH_USER_MODEL),
        ),
    ]
