# Generated by Django 3.0.8 on 2020-11-13 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ews', '0011_auto_20201113_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathing_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ews.BathingSpot')),
                ('station', models.ManyToManyField(related_name='models', to='ews.Station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
