# Generated by Django 3.0.8 on 2020-11-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0012_predictionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathingspot',
            name='description',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
