# Generated by Django 3.0.8 on 2020-11-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0013_bathingspot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodel',
            name='name',
            field=models.CharField(default='KWB_random_forest', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='station',
            field=models.ManyToManyField(blank=True, null=True, related_name='models', to='ews.Station'),
        ),
    ]
