# Generated by Django 3.0.8 on 2021-01-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0014_auto_20201113_1959'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featuredata',
            unique_together={('date', 'station')},
        ),
    ]
