# Generated by Django 3.0.8 on 2021-01-21 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ews', '0015_auto_20210117_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionmodel',
            name='station',
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('feature_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_type', to='ews.FeatureType')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='featuredata',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='ews.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictionmodel',
            name='site',
            field=models.ManyToManyField(blank=True, null=True, related_name='models', to='ews.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='featuredata',
            unique_together={('date', 'site')},
        ),
        migrations.RemoveField(
            model_name='featuredata',
            name='station',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
