# Generated by Django 3.1.5 on 2021-01-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0017_auto_20210121_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='location',
            new_name='geom',
        ),
    ]
