# Generated by Django 3.1.5 on 2021-01-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0019_auto_20210122_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredata',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
