# Generated by Django 3.1.5 on 2021-01-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0021_auto_20210122_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredata',
            name='value',
            field=models.DecimalField(decimal_places=10, max_digits=1000),
        ),
    ]
