# Generated by Django 3.1.5 on 2021-01-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0022_auto_20210122_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
