# Generated by Django 3.1.5 on 2021-01-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0024_auto_20210127_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredata',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=1000),
        ),
    ]
