# Generated by Django 3.1.5 on 2021-01-27 16:18

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0025_auto_20210127_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('geom', djgeojson.fields.MultiPolygonField()),
                ('feature_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='ews.featuretype')),
            ],
        ),
    ]
