# Generated by Django 3.1.5 on 2021-01-28 16:43

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0026_selectarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodel',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, related_name='models', to='ews.SelectArea'),
        ),
        migrations.AlterField(
            model_name='selectarea',
            name='geom',
            field=djgeojson.fields.PolygonField(),
        ),
    ]
