# Generated by Django 3.1.5 on 2021-02-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0028_auto_20210211_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodel',
            name='fit',
            field=models.BinaryField(null=True),
        ),
    ]
