# Generated by Django 3.1.5 on 2021-02-27 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0030_predictionmodel_predict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('abbreviation', models.CharField(max_length=6, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='featuredata',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable', to='ews.variable'),
        ),
    ]
