name: Django Security Check (on push)

on:
  push:
    branches:
      - master
      - main
      - dev


env:
  FAIL_LEVEL: INFO
  ENV_TYPE: venv
  APP_PATH:
  DEP_PATH: requirements.txt

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out current branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Install System Dependencies
      run: |
        sudo apt-get install binutils libproj-dev gdal-bin libgdal-dev libgdal1h
    - name: Scan Django settings for security issues
      id: check
      uses: mrustl/django-security-check@master
    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: security-check-output
        path: ${{ github.workspace }}/${{ env.APP_PATH  }}output.txt

